version: '3.7'

services:
  sample:
    build:
      context: .
      dockerfile: Dockerfile
    image: identify_frontend
    container_name: identify_frontend
    volumes:
      - '/usr/src/id-fe'
      - '/usr/src/id-fe/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
